# Generated by Django 5.0.7 on 2024-07-22 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techNews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100, unique=True)),
                ('source_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techNews.sources'),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
