# Generated by Django 5.0.7 on 2024-07-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techNews', '0002_sources_alter_news_source_delete_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(related_name='news', to='techNews.tags'),
        ),
        migrations.DeleteModel(
            name='NewsTag',
        ),
    ]
