# Generated by Django 5.0.7 on 2024-07-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techNews', '0003_news_tags_delete_newstag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='source_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(max_length=50),
        ),
    ]
